version: '3.8'

services:
  immich-redis:
    container_name: immich-redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /mnt/user/appdata/immich/redis:/data

  immich-postgres:
    container_name: immich-postgres
    image: tensorchord/pgvecto-rs:pg16-v0.3.0
    restart: unless-stopped
    environment:
      POSTGRES_USER: immich
      POSTGRES_PASSWORD: immich
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    ports:
      - "5433:5432"
    volumes:
      - /mnt/user/appdata/immich/postgres:/var/lib/postgresql/data

  immich:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:latest
    restart: unless-stopped
    ports:
      - "4080:3001"  # Immich runs on 3001 internally
    environment:
      # Database
      DB_HOSTNAME: 192.168.1.10
      DB_PORT: 5433
      DB_DATABASE_NAME: immich
      DB_USERNAME: immich
      DB_PASSWORD: immich
      
      # Redis
      REDIS_HOSTNAME: 192.168.1.10
      REDIS_PORT: 6379
      
      # Upload location
      UPLOAD_LOCATION: /photos
      
      # Machine Learning
      MACHINE_LEARNING_ENABLED: "false"  # Can enable later
      
      # Public URL (optional)
      # PUBLIC_IMMICH_SERVER_URL: http://192.168.1.10:4080
      
    volumes:
      - /mnt/user/photos:/photos  # Your photos share
      - /mnt/user/appdata/immich/config:/config
      - /mnt/user/appdata/immich/cache:/cache
    depends_on:
      - immich-redis
      - immich-postgres