#!/bin/bash

echo "Testing deploy script debug mode..."
echo ""
echo "1. Normal mode (no debug output):"
echo "./deploy-everything.sh"
echo ""
echo "2. Verbose mode (shows additional info):"
echo "./deploy-everything.sh -v"
echo ""
echo "3. Debug mode (shows all debug statements):"
echo "./deploy-everything.sh -d"
echo ""
echo "4. Debug mode with specific version:"
echo "./deploy-everything.sh -d 2.1.21"
echo ""
echo "5. Show help:"
echo "./deploy-everything.sh -h"
echo ""
echo "When a deployment fails, re-run with -d to see exactly where it failed!"